# Credits: Built on open-source libraries and papers acknowledged in README.md citations.

"""Image translation model architectures."""

from src.models.discriminators import PatchGANDiscriminator
from src.models.generators import ResNetGenerator, UNetGenerator
from src.models.unet import (
    BBDMUNet,
    BDBMUNet,
    BiBBDMUNet,
    CDTSDEUNet,
    DBIMUNet,
    DDBMUNet,
    DDIBUNet,
    I2SBDiffusersUNet,
    I2SBUNet,
    LBMUNet,
    create_model,
)
from src.models.dit import JIT_CONFIGS, JiTBackbone, SiTBackbone, SIT_CONFIGS
from src.models.stegogan import (
    ResnetMaskV1Generator,
    ResnetMaskV3Generator,
    NetMatchability,
)
from src.models.cut import (
    CUTGenerator,
    create_generator,
    create_discriminator,
    create_patch_sample_mlp,
)
from src.models.decent import (
    BNAFModel,
    FlowAdam,
    FlowConfig,
    MAF,
    MAFMOG,
    PatchDensityEstimator,
    compute_density_changing_loss,
    compute_flow_nll_loss,
)
from src.models.hneg_src import FeatureNormalize, PatchHDCELoss, SRCLoss
from src.models.flsesim import (
    ImageNetNormalization,
    ImagePool,
    PatchSim,
    SpatialCorrelativeLoss,
    VGG16FeatureExtractor,
    compute_spatial_correlative_loss,
)
from src.models.img2img_turbo import (
    CycleGANTurbo,
    Pix2PixTurbo,
    PRETRAINED_CYCLEGAN_TURBO,
    PRETRAINED_PIX2PIX_TURBO,
    PairedTurboDataset,
    UnpairedTurboDataset,
    build_transform,
    canny_from_pil,
    initialize_unet,
    initialize_vae,
)
from src.models.cyclegan_pix2pix import (
    CycleGANGenerator,
    GANLoss,
    Pix2PixGenerator,
    create_discriminator as create_cyclegan_pix2pix_discriminator,
    create_generator as create_cyclegan_pix2pix_generator,
    get_norm_layer,
    init_weights,
    load_upstream_generator_state,
)
from src.models.negcut import (
    LearnedPatchNCELoss,
    NegativeGenerator,
    NegativePlaceholder,
    create_negative_generator,
)
from src.models.unsb import (
    UNSBGenerator,
    UNSBDiscriminator,
    UNSBEnergyNet,
)
from src.models.local_diffusion import (
    LocalDiffusionUNet,
    ConditionEncoder,
)
from src.models.pix2pixhd import Pix2PixHDGenerator, Pix2PixHDGlobalGenerator
from src.models.stargan import StarGANGenerator, StarGANDiscriminator, StarGANResidualBlock
from src.models.fcdm import (
    FCDM,
    FCDM_S,
    FCDM_B,
    FCDM_L,
    FCDM_XL,
    FCDMImageCond,
    FCDM_MODELS,
)
from src.models.lddbm import (
    ModalityTranslationBridge,
    create_bridge,
    create_decoder,
    create_encoder,
)
from src.models.diffusionrouter import (
    DIFFUSIONROUTER_CLASS_NAMES,
    DIFFUSIONROUTER_DEFAULT_CHAIN,
    DiffusionRouterConfig,
    auto_route,
    compose_route,
    parse_class,
    parse_via_seq,
)

__all__ = [
    "UNetGenerator",
    "ResNetGenerator",
    "PatchGANDiscriminator",
    "I2SBUNet",
    "BBDMUNet",
    "BDBMUNet",
    "BiBBDMUNet",
    "CDTSDEUNet",
    "DBIMUNet",
    "DDBMUNet",
    "DDIBUNet",
    "I2SBDiffusersUNet",
    "LBMUNet",
    "JiTBackbone",
    "JIT_CONFIGS",
    "SiTBackbone",
    "SIT_CONFIGS",
    "ResnetMaskV1Generator",
    "ResnetMaskV3Generator",
    "NetMatchability",
    "CUTGenerator",
    "create_generator",
    "create_discriminator",
    "create_patch_sample_mlp",
    "FlowConfig",
    "PatchDensityEstimator",
    "BNAFModel",
    "FlowAdam",
    "MAF",
    "MAFMOG",
    "compute_density_changing_loss",
    "compute_flow_nll_loss",
    "FeatureNormalize",
    "SRCLoss",
    "PatchHDCELoss",
    "ImageNetNormalization",
    "ImagePool",
    "PatchSim",
    "SpatialCorrelativeLoss",
    "VGG16FeatureExtractor",
    "compute_spatial_correlative_loss",
    "CycleGANTurbo",
    "Pix2PixTurbo",
    "PRETRAINED_CYCLEGAN_TURBO",
    "PRETRAINED_PIX2PIX_TURBO",
    "PairedTurboDataset",
    "UnpairedTurboDataset",
    "build_transform",
    "canny_from_pil",
    "initialize_unet",
    "initialize_vae",
    "LearnedPatchNCELoss",
    "NegativeGenerator",
    "NegativePlaceholder",
    "create_negative_generator",
    "UNSBGenerator",
    "UNSBDiscriminator",
    "UNSBEnergyNet",
    "LocalDiffusionUNet",
    "ConditionEncoder",
    "Pix2PixHDGenerator",
    "Pix2PixHDGlobalGenerator",
    "StarGANGenerator",
    "StarGANDiscriminator",
    "StarGANResidualBlock",
    "FCDM",
    "FCDM_S",
    "FCDM_B",
    "FCDM_L",
    "FCDM_XL",
    "FCDMImageCond",
    "FCDM_MODELS",
    "ModalityTranslationBridge",
    "create_bridge",
    "create_decoder",
    "create_encoder",
    "CycleGANGenerator",
    "Pix2PixGenerator",
    "create_cyclegan_pix2pix_generator",
    "create_cyclegan_pix2pix_discriminator",
    "get_norm_layer",
    "init_weights",
    "load_upstream_generator_state",
    "GANLoss",
    "DIFFUSIONROUTER_CLASS_NAMES",
    "DIFFUSIONROUTER_DEFAULT_CHAIN",
    "DiffusionRouterConfig",
    "auto_route",
    "compose_route",
    "parse_class",
    "parse_via_seq",
]
